
server:
  http2:
    enabled: true
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxo
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none